#!/usr/bin/env python3
"""Generate the control plane's reference data from the sources of truth.

The UI documents the whole system — every CLI command, all five frozen
contracts, every JSON Schema, every contract enumeration. Hand-copying any of
that into a TypeScript file would guarantee it goes stale, and a reference that
is quietly wrong is worse than no reference at all: it is the file a reader
trusts precisely when they cannot check.

So none of it is written by hand. This reads:

    GUIDE.md              the command reference tables (syntax + purpose)
    kernel/cmd/aura/*.go  the usage block, to catch a command the guide forgot
    spec/c*.md            the five contracts, verbatim
    spec/schemas/**.json  every schema, verbatim
    spec/enums.yaml       the contract enumerations

    python scripts/gen_ui_reference.py           # write
    python scripts/gen_ui_reference.py --check   # fail if stale (CI)

Same contract as scripts/gen_ssot.py, and the same reason: two files that must
agree and nothing comparing them will drift, and the failure is silent.
"""
from __future__ import annotations

import argparse
import io
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ui" / "src" / "reference" / "generated.ts"

BANNER = """// Code generated by scripts/gen_ui_reference.py. DO NOT EDIT.
//
// Sources: GUIDE.md (command reference), kernel/cmd/aura/main.go (usage),
// spec/c1..c5-*.md, spec/schemas/**, spec/enums.yaml.
// Regenerate with: python scripts/gen_ui_reference.py
"""


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_lf(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)


# ── commands ─────────────────────────────────────────────────────────

def split_row(line: str) -> list[str]:
    """Split a markdown table row, honouring the \\| escape inside a cell."""
    parts, cur, i = [], "", 0
    while i < len(line):
        c = line[i]
        if c == "\\" and i + 1 < len(line) and line[i + 1] == "|":
            cur += "|"
            i += 2
            continue
        if c == "|":
            parts.append(cur)
            cur = ""
            i += 1
            continue
        cur += c
        i += 1
    parts.append(cur)
    return [p.strip() for p in parts]


def strip_md(s: str) -> str:
    """Flatten the inline markdown a table cell may carry into plain text.

    Links become their label: the reference view has no way to follow a
    GUIDE.md anchor, and rendering the raw `[text](#anchor)` would be noise.
    """
    s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)
    s = s.replace("`", "")
    s = re.sub(r"\*\*([^*]+)\*\*", r"\1", s)
    return s.strip()


def parse_commands(guide: str) -> list[dict]:
    """Parse the '## Command reference' section into groups of commands.

    A row beginning with '↳' continues the command above it — the guide uses
    them for flag groups too long for one line — so they attach to the previous
    entry as options rather than becoming phantom commands.
    """
    lines = guide.splitlines()
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == "## Command reference")
    except StopIteration:
        raise SystemExit("GUIDE.md has no '## Command reference' section")
    end = next(
        (i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")),
        len(lines),
    )

    groups: list[dict] = []
    current: dict | None = None
    for line in lines[start + 1 : end]:
        if line.startswith("### "):
            current = {"section": line[4:].strip(), "commands": []}
            groups.append(current)
            continue
        if not line.strip().startswith("|") or current is None:
            continue
        cells = [c for c in split_row(line) if c != ""]
        if len(cells) < 2:
            continue
        syntax, purpose = cells[0], cells[1]
        if set(syntax) <= set("-: "):  # the |---|---| separator
            continue
        if syntax.lower() == "command":  # the header row
            continue
        if syntax.startswith("↳"):
            if current["commands"]:
                current["commands"][-1]["options"].append(
                    {"syntax": strip_md(syntax.lstrip("↳ ").strip()), "purpose": strip_md(purpose)}
                )
            continue
        current["commands"].append(
            {"syntax": strip_md(syntax), "purpose": strip_md(purpose), "options": []}
        )
    return [g for g in groups if g["commands"]]


def parse_usage(main_go: str) -> list[str]:
    """Every `aura <verb>` line from the binary's own usage block.

    The block is a Go raw string that closes with a backtick on the *same* line
    as its last command (``aura version`)``), so the capture ends at the closing
    delimiter rather than at a newline before it — matching on the newline runs
    past the end and starts scraping unrelated format strings.
    """
    m = re.search(r"aura — cognitive runtime kernel\n(.*?)`\)", main_go, re.S)
    if not m:
        return []
    out = []
    for line in m.group(1).splitlines():
        s = line.strip().rstrip("`")
        if s.startswith("aura "):
            out.append(s)
    return out


def verb(syntax: str) -> str:
    parts = syntax.split()
    if len(parts) < 2:
        return ""
    return parts[1] if parts[0] == "aura" else ""


# ── contracts, schemas, enums ────────────────────────────────────────

CONTRACT_FILES = [
    ("C1", "c1-manifest.md", "Manifest"),
    ("C2", "c2-graph-ir.md", "Graph IR"),
    ("C3", "c3-channel.md", "Channel"),
    ("C4", "c4-ledger.md", "Ledger"),
    ("C5", "c5-attestation.md", "Attestation"),
]


def parse_contracts() -> list[dict]:
    out = []
    for cid, fname, title in CONTRACT_FILES:
        text = read(ROOT / "spec" / fname)
        status = ""
        m = re.search(r"^\*\*(Protocol major.*?)\*\*", text, re.M | re.S)
        if m:
            status = re.sub(r"\s+", " ", m.group(1)).strip()
        out.append({"id": cid, "title": title, "file": f"spec/{fname}", "status": status, "body": text})
    return out


def collect_schemas() -> list[dict]:
    out = []
    base = ROOT / "spec" / "schemas"
    for path in sorted(base.rglob("*.json")):
        rel = path.relative_to(base).as_posix()
        doc = json.loads(read(path))
        out.append(
            {
                "path": rel,
                "id": doc.get("$id", ""),
                "title": doc.get("title", ""),
                "body": read(path),
            }
        )
    return out


def collect_enums() -> dict:
    return yaml.safe_load(read(ROOT / "spec" / "enums.yaml"))


# ── emit ─────────────────────────────────────────────────────────────

def ts(value) -> str:
    """JSON is valid TypeScript for our shapes, and json.dumps escapes safely."""
    return json.dumps(value, ensure_ascii=False, indent=2)


def generate() -> str:
    guide = read(ROOT / "GUIDE.md")
    main_go = read(ROOT / "kernel" / "cmd" / "aura" / "main.go")

    groups = parse_commands(guide)
    documented = {verb(c["syntax"]) for g in groups for c in g["commands"]}
    documented.discard("")

    # A command the binary offers and the guide never mentions is a
    # documentation bug; surface it rather than silently shipping a reference
    # that claims to be complete.
    usage = parse_usage(main_go)
    undocumented = sorted({verb(u) for u in usage} - documented - {""})

    version = read(ROOT / "spec" / "VERSION").strip()

    parts = [
        BANNER,
        "",
        "export interface CommandOption { syntax: string; purpose: string }",
        "export interface Command { syntax: string; purpose: string; options: CommandOption[] }",
        "export interface CommandGroup { section: string; commands: Command[] }",
        "export interface Contract { id: string; title: string; file: string; status: string; body: string }",
        "export interface Schema { path: string; id: string; title: string; body: string }",
        "",
        f"export const SPEC_VERSION = {ts(version)};",
        "",
        "/** Every command in the guide's reference, grouped as the guide groups them. */",
        f"export const COMMANDS: CommandGroup[] = {ts(groups)};",
        "",
        "/** Verbs the binary's usage block offers that the guide does not document. */",
        f"export const UNDOCUMENTED: string[] = {ts(undocumented)};",
        "",
        "/** The binary's own usage block, verbatim. */",
        f"export const USAGE: string[] = {ts(usage)};",
        "",
        "/** The five frozen contracts, full text. */",
        f"export const CONTRACTS: Contract[] = {ts(parse_contracts())};",
        "",
        "/** Every JSON Schema under spec/schemas, full text. */",
        f"export const SCHEMAS: Schema[] = {ts(collect_schemas())};",
        "",
        "/** spec/enums.yaml — the contract enumerations. */",
        f"export const ENUMS = {ts(collect_enums())} as const;",
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = ap.parse_args()

    content = generate()
    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} is missing. Run: python scripts/gen_ui_reference.py")
            return 1
        if read(OUT).replace("\r\n", "\n") != content:
            print(f"{OUT.relative_to(ROOT)} is stale. Run: python scripts/gen_ui_reference.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is current.")
        return 0

    write_lf(OUT, content)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
