// Code generated from spec/enums.yaml and spec/VERSION. DO NOT EDIT.
// Regenerate with: python scripts/gen_ssot.py

package spec

// StdSchemas is every `std/*` JSON Schema, keyed by the reference a C1
// port declares (`std/text@1`). The value is the schema document verbatim.
//
// Verbatim matters: the grammar compiler and the payload validator both
// read these, and a reformatted copy would be a second source of truth for
// what a port accepts.
var StdSchemas = map[string]string{
	"std/api-request@1":  "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:api-request@1\",\n  \"title\": \"std/api-request@1\",\n  \"description\": \"A call into a projected or connected system.\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"params\": {\n      \"type\": \"object\"\n    },\n    \"query\": {\n      \"type\": \"object\"\n    },\n    \"headers\": {\n      \"type\": \"object\"\n    },\n    \"body\": {}\n  }\n}",
	"std/api-response@1": "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:api-response@1\",\n  \"title\": \"std/api-response@1\",\n  \"type\": \"object\",\n  \"required\": [\n    \"ok\"\n  ],\n  \"properties\": {\n    \"ok\": {\n      \"type\": \"boolean\"\n    },\n    \"status\": {\n      \"type\": \"integer\"\n    },\n    \"body\": {},\n    \"dry_run\": {\n      \"type\": \"boolean\"\n    },\n    \"request\": {\n      \"type\": \"object\"\n    },\n    \"error\": {\n      \"type\": \"string\"\n    }\n  }\n}",
	"std/audio-chunk@1":  "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:audio-chunk@1\",\n  \"title\": \"std/audio-chunk@1\",\n  \"description\": \"A slice of PCM audio. Signed 16-bit little-endian samples, base64-encoded. `final` marks an utterance or clause boundary, not the end of the stream \u2014 that is kind:done.\",\n  \"type\": \"object\",\n  \"required\": [\n    \"pcm_b64\",\n    \"sample_rate\"\n  ],\n  \"properties\": {\n    \"pcm_b64\": {\n      \"type\": \"string\",\n      \"contentEncoding\": \"base64\",\n      \"description\": \"PCM16LE samples, base64.\"\n    },\n    \"sample_rate\": {\n      \"type\": \"integer\",\n      \"minimum\": 8000,\n      \"maximum\": 192000\n    },\n    \"channels\": {\n      \"type\": \"integer\",\n      \"minimum\": 1,\n      \"maximum\": 2,\n      \"default\": 1\n    },\n    \"final\": {\n      \"type\": \"boolean\",\n      \"description\": \"End of an utterance or clause.\"\n    },\n    \"seq\": {\n      \"type\": \"integer\",\n      \"minimum\": 0,\n      \"description\": \"Chunk index within the stream, so a receiver can detect a gap when a realtime channel drops one.\"\n    },\n    \"ref\": {\n      \"type\": \"string\",\n      \"description\": \"Reserved. Forward compatibility for carrying samples out of band; unused in v1, and a receiver may ignore it.\"\n    }\n  }\n}",
	"std/confirmation@1": "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:confirmation@1\",\n  \"title\": \"std/confirmation@1\",\n  \"description\": \"A human-approval gate question (C2 rule 4).\",\n  \"type\": \"object\",\n  \"required\": [\n    \"question\",\n    \"options\",\n    \"held\"\n  ],\n  \"properties\": {\n    \"question\": {\n      \"type\": \"string\"\n    },\n    \"options\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"string\"\n      }\n    },\n    \"held\": {\n      \"type\": \"string\",\n      \"description\": \"Id of the envelope being held.\"\n    },\n    \"to_ref\": {\n      \"type\": \"string\",\n      \"description\": \"Graph node ref of the held delivery's destination (Phase 2, session resume).\"\n    },\n    \"to_port\": {\n      \"type\": \"string\",\n      \"description\": \"Ingress port of the held delivery's destination (Phase 2, session resume).\"\n    },\n    \"context_required\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"string\"\n      },\n      \"description\": \"Labels an approval must bind for this node to accept it (C4 v1.7). Labels only, never digests: those are computed by whoever rendered the material, which is not this node.\"\n    }\n  }\n}",
	"std/db-change@1":    "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:db-change@1\",\n  \"title\": \"std/db-change@1\",\n  \"description\": \"One row change from a database change-data-capture skill (e.g. example/sensorial/postgres-cdc) \u2014 one envelope per row change, not per transaction.\",\n  \"type\": \"object\",\n  \"required\": [\n    \"table\",\n    \"op\",\n    \"columns\"\n  ],\n  \"properties\": {\n    \"table\": {\n      \"type\": \"string\",\n      \"description\": \"Schema-qualified table name, e.g. \\\"public.orders\\\".\"\n    },\n    \"op\": {\n      \"enum\": [\n        \"insert\",\n        \"update\",\n        \"delete\"\n      ]\n    },\n    \"columns\": {\n      \"type\": \"object\",\n      \"description\": \"Column name -> value. For \\\"delete\\\", and for \\\"update\\\" unless the source table is REPLICA IDENTITY FULL, this is only the replica-identity columns (the primary key, by default) \u2014 a property of the source database, not data the skill lost.\"\n    },\n    \"lsn\": {\n      \"type\": \"string\",\n      \"description\": \"The source's log sequence number for this change, if the skill exposes one \u2014 for external resumability, not something the kernel interprets.\"\n    }\n  }\n}",
	"std/document@1":     "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:document@1\",\n  \"title\": \"std/document@1\",\n  \"description\": \"A whole file: an image, a WAV, a PDF.\",\n  \"type\": \"object\",\n  \"required\": [\n    \"mime\"\n  ],\n  \"properties\": {\n    \"mime\": {\n      \"type\": \"string\"\n    },\n    \"bytes_b64\": {\n      \"type\": \"string\",\n      \"contentEncoding\": \"base64\"\n    },\n    \"uri\": {\n      \"type\": \"string\"\n    }\n  }\n}",
	"std/plan@1":         "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:plan@1\",\n  \"title\": \"std/plan@1\",\n  \"type\": \"object\",\n  \"required\": [\n    \"reasoning\",\n    \"graph\"\n  ],\n  \"properties\": {\n    \"reasoning\": {\n      \"type\": \"string\"\n    },\n    \"graph\": {\n      \"type\": \"object\"\n    },\n    \"inputs\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"object\",\n        \"required\": [\n          \"port\",\n          \"schema\"\n        ],\n        \"properties\": {\n          \"port\": {\n            \"type\": \"string\"\n          },\n          \"schema\": {\n            \"type\": \"string\"\n          },\n          \"payload\": {}\n        }\n      }\n    }\n  }\n}",
	"std/status@1":       "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:status@1\",\n  \"title\": \"std/status@1\",\n  \"type\": \"object\",\n  \"required\": [\n    \"state\"\n  ],\n  \"properties\": {\n    \"state\": {\n      \"enum\": [\n        \"working\",\n        \"done\",\n        \"error\"\n      ]\n    },\n    \"detail\": {\n      \"type\": \"string\"\n    }\n  }\n}",
	"std/text@1":         "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:text@1\",\n  \"title\": \"std/text@1\",\n  \"description\": \"A piece of text. `text` is a DELTA to append: a streaming producer emits one of these per token and terminates with final:true. Consumers concatenate.\",\n  \"type\": \"object\",\n  \"required\": [\n    \"text\"\n  ],\n  \"properties\": {\n    \"text\": {\n      \"type\": \"string\"\n    },\n    \"final\": {\n      \"type\": \"boolean\",\n      \"description\": \"Last piece of this stream.\"\n    }\n  }\n}",
	"std/transcript@1":   "{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"$id\": \"aura:std:transcript@1\",\n  \"title\": \"std/transcript@1\",\n  \"description\": \"A speech-recognition hypothesis. Deliberately NOT std/text@1: `text` here REPLACES the previous hypothesis rather than appending to it, because a recogniser re-decodes its whole buffer and hypothesis 3 is not hypothesis 2 plus a suffix. Feeding partials into a consumer that concatenates would corrupt it.\",\n  \"type\": \"object\",\n  \"required\": [\n    \"text\",\n    \"final\"\n  ],\n  \"properties\": {\n    \"text\": {\n      \"type\": \"string\",\n      \"description\": \"The full hypothesis so far.\"\n    },\n    \"final\": {\n      \"type\": \"boolean\",\n      \"description\": \"True when the utterance ended and this is the settled transcript.\"\n    },\n    \"replace\": {\n      \"type\": \"boolean\",\n      \"description\": \"True (the norm) when this supersedes the previous hypothesis for the same utterance.\"\n    },\n    \"utterance\": {\n      \"type\": \"string\",\n      \"description\": \"Groups the partials of one utterance.\"\n    },\n    \"confidence\": {\n      \"type\": \"number\",\n      \"minimum\": 0,\n      \"maximum\": 1\n    }\n  }\n}",
}
